name: CreativeWarning
main: com.wwsean08.CreativeWarning.CreativeWarning
version: 1.0.0
website: www.wwsean08.com
author: wwsean08
description: this is a plugin for server admins to monitor what items players in creative mode give themselves
depends: [Spout]
permissions:
    CreativeWarning.ignore:
        description: ignores the user
        default: OP
    CreativeWarning.admin:
        description: players with this node get notified about blacklisted items in other players inventories
        default: OP
commands:
    CreativeWarning:
        description: This will reload the confix
        aliases: [cw]
        usage: /<command>